### ISSUE TITLE
One slide summary of NRI land team progress (ACCESS Community Workshop)

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/Land-workshop-prep#1]
Should be ready for Andy Hogg by the 28th.

Slide template coming soon.

**Comment by SeanBryan51** [comment]
Talking points:
- resolving code divergence in CABLE
    - benchcab v2.0.0 release 
    - CABLE - transition to GitHub
- JULES and CABLE (JAC)
    - Minimal regression testing for CABLE

**Comment by ccarouge** [comment]
Yes, we should.
We could have:

- resolving version divergences in CABLE:
    - benchcab release
    - new code management coming this year
- CABLE documentation overall
- AM3: UM v13.x coupled to CABLE 3.

Where I am still unsure is about CMIP7. I won't put it in and if Andy wants something we'll add to it.

**Comment by ccarouge** [comment]
@SeanBryan51 I've prepared [this slide](https://anu365.sharepoint.com/:p:/s/ACCESS-NRI/ESkCU4juykxAlTbLv7wLsZABN0058J4ZhCawsb9JXKfhzA?e=JHjkt2)
I have intentionally left the title bare as I'm thinking Andy might want to harmonise all the slides. 
I'm not sure about the AM3 work since only Jhan has worked on this. But I'll left Andy to decide to put it in or not.

I'm still wondering about adding the JaC work. 

@bschroeter FYI, you can look at the slide but I don't expect you to have much to say about it yet.

**Comment by MartinDix** [comment]
>     * AM3: UM v13.x coupled to CABLE 3.

This is very much still work in progress

**Comment by ccarouge** [comment]
@MartinDix I have taken it out anyway as we haven't worked on it yet. 
Anyway, this is done!
